# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# react-native-live2d: keep all Live2D Cubism classes (JNI native methods + reflection)
# Without this, R8 minify obfuscates class names and Live2D native bindings break.
-keep class com.live2d.sdk.** { *; }
-keep class expo.modules.live2d.** { *; }
-keepclassmembers class com.live2d.sdk.** {
    native <methods>;
}
-keepclassmembers class * implements com.live2d.sdk.** {
    public *;
}

# Suppress R8 missing-class warnings for expo-modules interfaces and the
# Live2D RN bridge (these are pulled in via React autolinking and resolved
# at runtime — R8 sees the references but doesn't need to ship them
# directly because the implementing modules handle them at runtime).
-dontwarn expo.modules.core.interfaces.services.KeepAwakeManager
-dontwarn expo.modules.interfaces.filesystem.FilePermissionModuleInterface
-dontwarn expo.modules.interfaces.filesystem.Permission
-dontwarn expo.modules.live2d.ReactNativeLive2dModule

# expo-modules-kotlin types/descriptors package: AssetModule.definition()
# calls into these classes at runtime via Kotlin compiler-generated bytecode.
# R8 sees the references but cannot resolve the classes through the
# normal Java call graph (they're initialized via reflection / object
# pool), so it strips them and the app crashes with NoClassDefFoundError
# on first launch. Keep the whole namespace to be safe.
-keep class expo.modules.kotlin.** { *; }
-keep class expo.modules.kotlin.types.** { *; }
-keep class expo.modules.kotlin.types.descriptors.** { *; }

# expo-sharing: the module entry class is referenced by ExpoModulesPackageList
# at runtime, but R8 partial mode may treat it as removable. Keep it explicit.
-keep class expo.modules.sharing.** { *; }

# Add any project specific keep options here:
