/**
 * /ai-practice/add-custom-guide — multi-turn AI 陪练 conversation
 * guide for 自定义话题.
 *
 * UX model: the user CANNOT type free text on this page (the
 * natural-language entry handles that). Instead, the AI asks one
 * question at a time, and the user answers by tapping a chip.
 * The options for each turn are generated by the LLM itself
 * (see lib/ai/scene-options-generator.ts) — there is NO
 * hard-coded scene/person/situation map.
 *
 *   - LLM keeps the option set current and exhaustive (a hard-coded
 *     map can never be as complete as the LLM's world knowledge).
 *   - LLM-seen context (previous turn picks) keeps options
 *     contextually relevant without us hand-curating the
 *     (scene, person, situation) tuples.
 *
 * Trade-off: every turn costs one LLM round-trip (~2-3 s of
 * loading). The loading state is shown explicitly so the user
 * knows the AI is "thinking" rather than the app being broken.
 *
 * Turn order (3 LLM turns + 1 static turn):
 *   1. 地点   — LLM-generate scene list
 *   2. 人物   — LLM-generate person list (sees scene)
 *   3. 情况   — LLM-generate situation list (sees scene + person)
 *   4. 数量   — 3 / 5 / 8 hard-coded (no LLM needed)
 *
 * Once all 4 turns are answered, the primary "生成" button
 * appears and opens the shared GenerateModal.
 *
 * "自己写" escape hatch: every turn offers a "✏️ 自己写" chip
 * that bounces the user back to /add-custom (natural-language
 * entry). The guide does NOT support partial free-write state.
 *
 * "↻" re-pick: each answered turn shows a refresh button that
 * drops this turn and all later turns, returning to a re-pick on
 * this turn. Earlier turns are preserved.
 */

import {
  View,
  Text,
  StyleSheet,
  Pressable,
  ScrollView,
  ActivityIndicator,
  Alert,
  Modal,
  TextInput,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ArrowLeft,
  Pencil,
  RefreshCw,
  Sparkles,
  X,
} from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, spacing, borderRadius, fontSize, fontWeight } from '../../constants/theme';
import {
  generateSceneOptions,
  type OptionsTurn,
  type SceneOption,
} from '../../lib/ai/scene-options-generator';
import { GenerateModal } from './generate-modal';

const COUNT_OPTIONS: ReadonlyArray<number> = [3, 5, 8];
const DEFAULT_COUNT = 5;
const MAX_SELF_WRITE_LENGTH = 24;

const SELF_WRITE_PROMPTS: Record<OptionsTurn, string> = {
  scene: '输入场景（比如：健身房、宠物店、4S 店）',
  person: '输入人物（比如：教练、前台、技师）',
  situation: '输入情况（比如：办卡咨询、车辆保养）',
};

interface Turn {
  kind: OptionsTurn | 'count';
  aiText: string;
  /** Null = not yet loaded; non-null = the option list to show. */
  options: ReadonlyArray<SceneOption | number> | null;
  selectedKey: string | number | null;
}

function buildInitialTurns(): Turn[] {
  return [
    {
      kind: 'scene',
      aiText: '你想练什么场景？',
      options: null,
      selectedKey: null,
    },
  ];
}

function buildPersonTurn(scene: string): Turn {
  return {
    kind: 'person',
    aiText: `在「${scene}」里，你通常需要跟谁对话？`,
    options: null,
    selectedKey: null,
  };
}

function buildSituationTurn(scene: string, person: string): Turn {
  return {
    kind: 'situation',
    aiText: `跟「${person}」一般是哪种情况？`,
    options: null,
    selectedKey: null,
  };
}

function buildCountTurn(): Turn {
  return {
    kind: 'count',
    aiText: '生成几个话题？',
    options: COUNT_OPTIONS,
    selectedKey: null,
  };
}

export default function AiPracticeAddCustomGuidePage() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [turns, setTurns] = useState<Turn[]>(buildInitialTurns);
  const [isGenerateOpen, setIsGenerateOpen] = useState(false);
  const [userLevel, setUserLevel] = useState('B1');
  // Self-write modal: when the user taps "自己写" on a turn, we
  // open a tiny inline modal where they type the missing value.
  // `null` = closed; otherwise it carries the turn's kind so the
  // input box can show a context-aware placeholder.
  const [selfWriteTurn, setSelfWriteTurn] = useState<{
    turnIndex: number;
    kind: OptionsTurn;
  } | null>(null);
  const [selfWriteInput, setSelfWriteInput] = useState('');
  // Session-scoped dedup list. Every key the LLM has produced
  // across the whole guide (including re-generations of the same
  // turn) is accumulated here and fed back to the LLM as a HARD
  // CONSTRAINT on the next call. turn.options is NOT enough —
  // re-pick (↻) wipes a turn's options, so the LLM would otherwise
  // happily re-suggest the same 4S 店 / 宠物店 / 驾校 it just gave
  // us 5 seconds ago. The Set lives across the whole page life
  // and resets only when the page is unmounted.
  const [sessionAvoidList, setSessionAvoidList] = useState<ReadonlyArray<string>>([]);

  // Track which turn-index we've already kicked off an LLM call
  // for, so re-renders don't fire duplicate requests.
  const loadedRef = useRef<Set<number>>(new Set());

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const AsyncStorage = (await import('@react-native-async-storage/async-storage')).default;
        const level = (await AsyncStorage.getItem('user_level')) || 'B1';
        if (!cancelled) setUserLevel(level);
      } catch {
        // B1 default.
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // ── LLM-driven options loader ─────────────────────────────
  // Watch turns; whenever a turn has options=null and isn't the
  // 'count' static turn, fire the LLM call. `loadedRef` prevents
  // double-firing on re-renders. The session-scoped
  // `sessionAvoidList` is fed to every call so re-picks and later
  // turns never see the same 5-8 names again.
  useEffect(() => {
    const pendingIndex = turns.findIndex(
      (t) => t.options === null && t.kind !== 'count',
    );
    if (pendingIndex === -1) return;
    if (loadedRef.current.has(pendingIndex)) return;

    const turn = turns[pendingIndex];
    const context: { scene?: string; person?: string } = {};
    for (const t of turns) {
      if (t.selectedKey == null) continue;
      const key = String(t.selectedKey);
      if (t.kind === 'scene') context.scene = key;
      else if (t.kind === 'person') context.person = key;
    }

    loadedRef.current.add(pendingIndex);

    (async () => {
      try {
        const options = await generateSceneOptions({
          turn: turn.kind as OptionsTurn,
          context,
          userLevel,
          avoidList: sessionAvoidList,
        });
        // Accumulate every key the LLM produced this call into the
        // session avoid list. Future calls (this turn's ↻, or
        // later turns) get the full history — no repeats.
        const newKeys = options
          .filter((o): o is SceneOption => typeof o !== 'number')
          .map((o) => o.key);
        if (newKeys.length > 0) {
          setSessionAvoidList((prev) => {
            const merged = new Set(prev);
            for (const k of newKeys) merged.add(k);
            return Array.from(merged);
          });
        }
        setTurns((prev) => {
          if (prev[pendingIndex]?.kind !== turn.kind) return prev;
          const next = [...prev];
          next[pendingIndex] = { ...next[pendingIndex], options };
          return next;
        });
      } catch (error) {
        console.warn('[add-custom-guide] LLM options failed', error);
      }
    })();
  }, [turns, userLevel, sessionAvoidList]);

  // ── Derived state ─────────────────────────────────────────
  const currentTurnIndex = useMemo(
    () => turns.findIndex((t) => t.selectedKey === null),
    [turns],
  );
  const isComplete = currentTurnIndex === -1;
  const collected = useMemo(() => {
    const out: { scene?: string; person?: string; situation?: string; count?: number } = {};
    turns.forEach((t) => {
      if (t.selectedKey == null) return;
      if (t.kind === 'scene') out.scene = String(t.selectedKey);
      if (t.kind === 'person') out.person = String(t.selectedKey);
      if (t.kind === 'situation') out.situation = String(t.selectedKey);
      if (t.kind === 'count') out.count = Number(t.selectedKey);
    });
    return out;
  }, [turns]);

  // ── Mutators ──────────────────────────────────────────────
  const handleSelect = useCallback((turnIndex: number, key: string | number) => {
    setTurns((prev) => {
      const next = [...prev];
      const target = next[turnIndex];
      next[turnIndex] = { ...target, selectedKey: key };

      // Push the next-turn placeholder if this was the last turn
      // and the turn kind needs another LLM call.
      const isLastTurn = turnIndex === prev.length - 1;
      if (!isLastTurn) return next;

      if (target.kind === 'scene') {
        next.push(buildPersonTurn(String(key)));
      } else if (target.kind === 'person') {
        next.push(buildSituationTurn(collected.scene ?? '', String(key)));
      } else if (target.kind === 'situation') {
        next.push(buildCountTurn());
      }
      // 'count' is final — no next turn.
      return next;
    });
  }, [collected.scene]);

  const handleSelfWriteOpen = useCallback((turnIndex: number, kind: OptionsTurn) => {
    setSelfWriteInput('');
    setSelfWriteTurn({ turnIndex, kind });
  }, []);

  const handleSelfWriteClose = useCallback(() => {
    setSelfWriteTurn(null);
    setSelfWriteInput('');
  }, []);

  const handleRegenOptions = useCallback((turnIndex: number) => {
    setTurns((prev) => {
      const target = prev[turnIndex];
      if (!target) return prev;
      const next = [...prev];
      next[turnIndex] = { ...target, options: null };
      return next;
    });
    // Clear the dedup guard so the loader effect fires again with
    // a fresh LLM call. The LLM will likely return a different
    // option set (temperature=0.7).
    loadedRef.current.delete(turnIndex);
  }, []);

  const handleSelfWriteConfirm = useCallback(() => {
    if (!selfWriteTurn) return;
    const trimmed = selfWriteInput.trim();
    if (!trimmed) {
      // Empty input — do nothing, the user can keep typing or
      // dismiss the modal with the X button.
      return;
    }
    const { turnIndex, kind } = selfWriteTurn;
    setSelfWriteTurn(null);
    setSelfWriteInput('');

    // Push the same value into the turn and append the next turn
    // (mirrors handleSelect's downstream logic).
    setTurns((prev) => {
      const next = [...prev];
      const target = next[turnIndex];
      next[turnIndex] = { ...target, selectedKey: trimmed };

      const isLastTurn = turnIndex === prev.length - 1;
      if (!isLastTurn) return next;

      if (kind === 'scene') {
        next.push(buildPersonTurn(trimmed));
      } else if (kind === 'person') {
        // Find the prior scene for the next-turn prompt copy.
        const priorScene = next
          .slice(0, turnIndex)
          .reverse()
          .find((t) => t.kind === 'scene')?.selectedKey;
        next.push(buildSituationTurn(String(priorScene ?? ''), trimmed));
      } else if (kind === 'situation') {
        next.push(buildCountTurn());
      }
      return next;
    });
  }, [selfWriteInput, selfWriteTurn]);

  const handleOpenGenerate = useCallback(() => {
    if (!isComplete) return;
    setIsGenerateOpen(true);
  }, [isComplete]);

  const handleCloseGenerate = useCallback(() => {
    setIsGenerateOpen(false);
  }, []);

  // ── Render helpers ───────────────────────────────────────
  const renderOptionChip = (
    option: SceneOption | number,
    onPress: () => void,
  ) => {
    if (typeof option === 'number') {
      return (
        <Pressable
          key={`opt-num-${option}`}
          style={styles.optionChip}
          onPress={onPress}
        >
          <Text style={styles.optionChipText}>{option} 个</Text>
        </Pressable>
      );
    }
    return (
      <Pressable
        key={`opt-${option.key}`}
        style={styles.optionChip}
        onPress={onPress}
      >
        <Text style={styles.optionEmoji}>{option.emoji}</Text>
        <Text style={styles.optionChipText}>{option.label}</Text>
      </Pressable>
    );
  };

  return (
    <>
      <Stack.Screen
        options={{
          headerShown: true,
          title: 'AI 引导',
          headerShadowVisible: false,
          headerStyle: { backgroundColor: colors.background },
          headerTitleStyle: { color: colors.text.primary, fontSize: fontSize.lg, fontWeight: fontWeight.semibold },
          headerLeft: () => (
            <Pressable hitSlop={8} onPress={() => router.back()} style={styles.headerBack}>
              <ArrowLeft size={20} color={colors.text.primary} />
            </Pressable>
          ),
        }}
      />
      <View style={styles.container}>
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={[styles.scrollContent, { paddingBottom: Math.max(160, insets.bottom + 96) }]}
          showsVerticalScrollIndicator={false}
        >
          {turns.map((turn, turnIndex) => {
            const isCurrent = turn.selectedKey === null;
            // Look up the selected chip so we can render its emoji
            // + label. If the user used "自己写" the typed value
            // is NOT in turn.options (it was set directly), so we
            // fall back to selectedKey as plain text. This is the
            // only branch that needs the fallback — every other
            // turn stores its chip inside turn.options.
            const selectedOption = !isCurrent
              ? turn.options?.find((o) =>
                  typeof o === 'number' ? o === turn.selectedKey : o.key === turn.selectedKey,
                )
              : null;
            const selectedDisplay = !isCurrent
              ? selectedOption !== undefined
                ? (typeof selectedOption === 'number'
                    ? `${selectedOption} 个`
                    : `${(selectedOption as SceneOption).emoji} ${(selectedOption as SceneOption).label}`)
                : String(turn.selectedKey ?? '')
              : '';
            return (
              <View key={`turn-${turnIndex}-${turn.kind}`} style={styles.turnBlock}>
                {/* AI 气泡 + 重新生成按钮 */}
                <View style={styles.aiRow}>
                  <View style={styles.botAvatar}>
                    <Text style={styles.botAvatarText}>AI</Text>
                  </View>
                  <View style={styles.aiBubbleWrap}>
                    <View style={styles.aiBubble}>
                      <Text style={styles.aiText}>{turn.aiText}</Text>
                    </View>
                    {/* ↻ 重新生成：当前轮已加载 options 时显示。
                        loading 状态不显示（已经在加载了）。 */}
                    {isCurrent && turn.options ? (
                      <Pressable
                        hitSlop={8}
                        onPress={() => handleRegenOptions(turnIndex)}
                        style={styles.regenBtn}
                      >
                        <RefreshCw size={13} color={colors.text.secondary} />
                      </Pressable>
                    ) : null}
                  </View>
                </View>

                {/* 当轮：loading / options / 用户已选 */}
                {isCurrent ? (
                  turn.kind === 'count' || turn.options ? (
                    <View style={styles.optionGrid}>
                      {turn.options!.map((opt) =>
                        renderOptionChip(
                          opt,
                          () => handleSelect(
                            turnIndex,
                            typeof opt === 'number' ? opt : opt.key,
                          ),
                        ),
                      )}
                      <Pressable
                        key="opt-self-write"
                        style={[styles.optionChip, styles.optionChipSelfWrite]}
                        onPress={() => handleSelfWriteOpen(turnIndex, turn.kind as OptionsTurn)}
                      >
                        <Pencil size={14} color={colors.text.secondary} />
                        <Text style={styles.optionChipSelfWriteText}>自己写</Text>
                      </Pressable>
                    </View>
                  ) : (
                    <View style={styles.loadingBlock}>
                      <ActivityIndicator size="small" color={colors.primary} />
                      <Text style={styles.loadingText}>AI 正在想合适的选项…</Text>
                      <Pressable
                        onPress={() => handleSelfWriteOpen(turnIndex, turn.kind as OptionsTurn)}
                        hitSlop={6}
                        style={styles.loadingSelfWriteLink}
                      >
                        <Text style={styles.loadingSelfWriteText}>跳过，自己写</Text>
                      </Pressable>
                    </View>
                  )
                ) : (
                  /* 用户气泡 (答完了，没有重新选按钮 — 选了就不能反悔) */
                  <View style={styles.userRow}>
                    <View style={styles.userBubble}>
                      <Text style={styles.userText}>{selectedDisplay}</Text>
                    </View>
                  </View>
                )}
              </View>
            );
          })}

          {/* 全部答完 → 主按钮 */}
          {isComplete ? (
            <Pressable style={styles.primaryBtn} onPress={handleOpenGenerate}>
              <Sparkles size={18} color="#FFFFFF" />
              <Text style={styles.primaryBtnText}>
                生成 {collected.count ?? DEFAULT_COUNT} 个话题
              </Text>
            </Pressable>
          ) : null}
        </ScrollView>
      </View>

      <Modal
        visible={selfWriteTurn !== null}
        transparent
        animationType="fade"
        onRequestClose={handleSelfWriteClose}
      >
        <KeyboardAvoidingView
          style={styles.selfWriteOverlay}
          behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        >
          <Pressable style={styles.selfWriteBackdrop} onPress={handleSelfWriteClose} />
          <View style={styles.selfWriteSheet}>
            <View style={styles.selfWriteHeader}>
              <Text style={styles.selfWriteTitle}>
                {selfWriteTurn ? SELF_WRITE_PROMPTS[selfWriteTurn.kind].split('（')[0] : '自己写'}
              </Text>
              <Pressable hitSlop={8} onPress={handleSelfWriteClose}>
                <X size={20} color={colors.text.secondary} />
              </Pressable>
            </View>
            <Text style={styles.selfWriteHint}>
              {selfWriteTurn ? SELF_WRITE_PROMPTS[selfWriteTurn.kind] : ''}
            </Text>
            <TextInput
              style={styles.selfWriteInput}
              value={selfWriteInput}
              onChangeText={(text) => setSelfWriteInput(text.slice(0, MAX_SELF_WRITE_LENGTH))}
              placeholder="在这里输入"
              placeholderTextColor={colors.text.tertiary}
              maxLength={MAX_SELF_WRITE_LENGTH}
              autoFocus
              returnKeyType="done"
              onSubmitEditing={handleSelfWriteConfirm}
            />
            <View style={styles.selfWriteActions}>
              <Pressable
                style={styles.selfWriteCancel}
                onPress={handleSelfWriteClose}
                hitSlop={6}
              >
                <Text style={styles.selfWriteCancelText}>取消</Text>
              </Pressable>
              <Pressable
                style={[
                  styles.selfWriteConfirm,
                  !selfWriteInput.trim() && styles.selfWriteConfirmDisabled,
                ]}
                onPress={handleSelfWriteConfirm}
                hitSlop={6}
                disabled={!selfWriteInput.trim()}
              >
                <Text style={styles.selfWriteConfirmText}>确定</Text>
              </Pressable>
            </View>
          </View>
        </KeyboardAvoidingView>
      </Modal>

      <GenerateModal
        visible={isGenerateOpen}
        onClose={handleCloseGenerate}
        prompt={[
          collected.scene,
          collected.person,
          collected.situation,
        ].filter(Boolean).join(' / ')}
        // CRITICAL: pass a single concatenated string so the
        // downstream `generateDailyScenariosStream` routes to
        // `buildCustomQueryPrompt` ("Generate N scenarios all
        // based on this exact situation"). If we pass 3 separate
        // words, the LLM treats each as an independent domain tag
        // and just restates them as card titles — that's the
        // "球场入口 / 认识新球友 / 约下次踢球" bug we saw on
        // 2026-08-13.
        interests={(() => {
          const merged = [
            collected.scene,
            collected.person,
            collected.situation,
          ].filter(Boolean).join('、');
          return merged.length > 10 ? [merged] : ['日常场景练习'];
        })()}
        userLevel={userLevel}
        count={collected.count ?? DEFAULT_COUNT}
      />
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerBack: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },

  turnBlock: {
    marginBottom: spacing.lg,
  },

  // AI 气泡
  aiRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  botAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  botAvatarText: {
    fontSize: 11,
    fontWeight: fontWeight.bold,
    color: '#FFFFFF',
  },
  aiBubbleWrap: {
    flex: 1,
    position: 'relative',
  },
  aiBubble: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    borderTopLeftRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
    paddingRight: 36, // 给 ↻ 按钮留位
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  aiText: {
    fontSize: fontSize.sm,
    color: colors.text.primary,
    lineHeight: 20,
  },
  regenBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(0, 0, 0, 0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // 选项 chip 网格
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: spacing.sm,
    marginLeft: 44, // align under the AI bubble (32 avatar + 12 gap)
  },
  optionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  optionChipSelfWrite: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
  },
  optionEmoji: {
    fontSize: 16,
    lineHeight: 18,
  },
  optionChipText: {
    fontSize: fontSize.sm,
    color: colors.text.primary,
    fontWeight: fontWeight.medium,
  },
  optionChipSelfWriteText: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    fontWeight: fontWeight.medium,
  },

  // Loading state
  loadingBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
    marginLeft: 44,
    flexWrap: 'wrap',
  },
  loadingText: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
  },
  loadingSelfWriteLink: {
    paddingVertical: 2,
  },
  loadingSelfWriteText: {
    fontSize: fontSize.xs,
    color: colors.text.tertiary,
    textDecorationLine: 'underline',
  },

  // 用户气泡
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    marginTop: spacing.sm,
  },
  userBubble: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    borderTopRightRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
    maxWidth: '75%',
  },
  userText: {
    fontSize: fontSize.sm,
    color: '#FFFFFF',
    fontWeight: fontWeight.medium,
  },
  // 主按钮
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    marginTop: spacing.lg,
  },
  primaryBtnText: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: '#FFFFFF',
  },

  // ── "自己写" 弹窗 ──────────────────────────────────────
  selfWriteOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  selfWriteBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  selfWriteSheet: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  selfWriteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selfWriteTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
  },
  selfWriteHint: {
    fontSize: fontSize.xs,
    color: colors.text.tertiary,
    lineHeight: 18,
  },
  selfWriteInput: {
    marginTop: spacing.xs,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: fontSize.base,
    color: colors.text.primary,
    backgroundColor: '#F8FAFC',
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  selfWriteActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  selfWriteCancel: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
  },
  selfWriteCancelText: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    fontWeight: fontWeight.medium,
  },
  selfWriteConfirm: {
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
  },
  selfWriteConfirmDisabled: {
    opacity: 0.4,
  },
  selfWriteConfirmText: {
    fontSize: fontSize.sm,
    color: '#FFFFFF',
    fontWeight: fontWeight.bold,
  },
});
